apiVersion: v1
kind: Service
metadata:
  name: rsyslog
  labels:
    app: rsyslog
spec:
  selector:
    app: rsyslog
  ports:
  - name: syslog-tcp
    port: 514
    protocol: TCP
    targetPort: 10514
  - name: syslog-udp
    port: 514
    protocol: UDP
    targetPort: 10514
  - name: http-metrics
    port: 8080
    protocol: TCP
    targetPort: http
