global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.yml
        refresh_interval: 5m
    metrics_path: /metrics
    scrape_interval: 15s
