# Copyright 2020 Rainer Gerhards and Others
#
# https://github.com/rsyslog/rsyslog-pkg-ubuntu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# References:
#
# https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#github-actions-notification-options
# https://github.com/settings/notifications
# https://software.opensuse.org//download.html?project=home%3Argerhards&package=rsyslog


---
name: check systemd journal

on:
  pull_request:

jobs:
  check_run:
    runs-on: ubuntu-20.04
    timeout-minutes: 30

    steps:
      - name: git checkout project
        uses: actions/checkout@v1

      - name: add extra dependencies
        run: |
          echo 'deb http://download.opensuse.org/repositories/home:/rgerhards/xUbuntu_20.04/ /' \
              | sudo tee /etc/apt/sources.list.d/home:rgerhards.list
          curl -fsSL https://download.opensuse.org/repositories/home:rgerhards/xUbuntu_20.04/Release.key \
              | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home:rgerhards.gpg > /dev/null
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-gnutls-dev \
            libdbi-dev \
            libestr-dev \
            libgcrypt20-dev \
            libglib2.0-dev \
            libgnutls28-dev \
            libgrok1 libgrok-dev \
            libhiredis-dev \
            libkrb5-dev \
            liblognorm-dev \
            liblz4-dev \
            libmongoc-dev \
            libmysqlclient-dev \
            libnet1-dev \
            libpcap-dev \
            librelp-dev \
            libsasl2-dev \
            libsnmp-dev \
            libssl-dev \
            libsystemd-dev \
            libtool \
            libtool-bin \
            logrotate \
            lsof \
            make \
            mysql-server \
            net-tools \
            pkg-config \
            postgresql-client libpq-dev \
            python3-pip \
            python3-pysnmp4 \
            python-docutils  \
            software-properties-common \
            uuid-dev \
            valgrind \
            vim \
            wget \
            librdkafka-dev \
            zlib1g-dev

      - name: build dependencies which require that
        run: |
             mkdir helper-projects && \
             cd helper-projects && \
             git clone https://github.com/rsyslog/librelp.git && \
             cd librelp && \
             autoreconf -fi && \
             ./configure --prefix=/usr --enable-compile-warnings=yes --libdir=/usr/lib --includedir=/usr/include && \
             make -j && \
             sudo make install && \
             cd .. && \
             rm -r librelp && \
             cd ..

      - name: prepare for build
        run: |
          autoreconf -fvi
          ./configure --enable-silent-rules --enable-testbench \
             --enable-imdiag --disable-imdocker --disable-imfile --disable-default-tests\
             --disable-impstats --disable-imptcp --disable-mmanon --disable-mmaudit --disable-mmfields \
             --disable-mmjsonparse --disable-mmpstrucdata --disable-mmsequence --disable-mmutf8fix \
             --disable-mail --disable-omprog --disable-improg --disable-omruleset --enable-omstdout \
             --disable-omuxsock --disable-pmaixforwardedfrom --disable-pmciscoios --disable-pmcisconames \
             --disable-pmlastmsg --disable-pmsnare --disable-libgcrypt --disable-mmnormalize \
             --disable-omudpspoof --disable-relp --disable-mmsnmptrapd --disable-gnutls --enable-usertools \
             --disable-mysql --enable-valgrind --enable-omjournal --enable-libsystemd=yes \
             --disable-mmkubernetes --enable-imjournal --disable-omkafka --disable-imkafka \
             --disable-ommongodb --disable-omrabbitmq --enable-journal-tests --disable-mmdarwin \
             --enable-compile-warnings=error --disable-helgrind --disable-uuid --disable-fmhttp

      - name: build
        run: |
          make -j

      - name: make check
        run: |
          make -j8 check

      - name: show error logs (if we errored)
        if:  ${{ failure() || cancelled() }}
        run: |
          devtools/gather-check-logs.sh
          cat failed-tests.log
